# Generated by Django 3.2.23 on 2023-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='holiday_type',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('couples', 'Couples'), ('group', 'Group'), ('girls', 'Girls'), ('guys', 'Guys'), ('work', 'Work'), ('family', 'Family')], default='solo', max_length=10),
        ),
    ]
