# Generated by Django 3.2.23 on 2023-11-24 17:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_experience',
            field=models.CharField(choices=[('newbie', 'Newbie traveller'), ('intermediate', 'Intermediate traveller'), ('expert', 'Expert traveller')], default='newbie', max_length=20),
        ),
    ]
